name: mpflutter_wechat_webview
description: "The web view widget in wechat miniprogram"
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mpflutter_core: ">=2.0.0"
  mpflutter_wechat_api: ">=2.0.0"